### ISSUE TITLE
Using "Tooltips" is giving Warning in console

### ISSUE THREAD

**Issue by kambanwait** [algolia/react-nouislider#21] opened 2016-04-08 17:16 UTC
When I use the following:

`<Nouislider tooltips={{to: function(value){return Math.round(parseInt(value));}}} />`

I'm presented with the following warning in console:

`Warning: Failed propType: Invalid prop`tooltips`supplied to`Nouislider`. Check the render method of`exports`.`

**Comment by vvo** [comment] 2016-04-13 15:43
duplicate of #20 lets solve this here

**Closed as completed by vvo** 2016-04-13 15:43 UTC
